saucelabs/saucectl-cypress-example

.sauce/config.yml
Add example configuration bloc for artifacts downloads
```
artifacts:
download:
when: always
match:
- console.log
directory: ./artifacts/
```
=> Add example for Artifacts

.gitignore, .sauce/config.yml, cypress/integration/examples/assertions.spec.js, cypress/integration/examples/traversal.spec.js, examples/cucumber/.sauce/config.yml, examples/typescript/.sauce/config.yml
=> [DEVX-1244] Demo Sharding

.github/workflows/test.yml, examples/README.md, examples/allure-plugin/.sauce/config.yml, examples/allure-plugin/.sauceignore, examples/allure-plugin/README.md, examples/allure-plugin/cypress.json, examples/allure-plugin/cypress/fixtures/example.json, examples/allure-plugin/cypress/integration/examples/actions.spec.js, examples/allure-plugin/cypress/plugins/index.js, examples/allure-plugin/cypress/scripts/runner.js, examples/allure-plugin/cypress/support/index.js, examples/allure-plugin/cypress/tsconfig.json
e.g. https://app.saucelabs.com/tests/8721d11ba79a41c084d0b289a6b229ed
=> [DEVX-1513] Add cypress allure plguin example

examples/allure-plugin/.sauce/config.yml, examples/cucumber/.sauce/config.yml, examples/cucumber/README.md, examples/cucumber/cypress.json, examples/cucumber/cypress/integration/actions.feature, examples/cucumber/cypress/integration/actions.js, examples/cucumber/cypress/integration/assertions.feature, examples/cucumber/cypress/integration/assertions.js, examples/cucumber/cypress/plugins/index.js, examples/cucumber/package-lock.json, examples/cucumber/package.json
There were some breaking changes made to the cucumber preprocessor package. Update the example to use the latest.
=> Update cucumber preprocessor to latest

.github/CODEOWNERS, .github/ISSUE_TEMPLATE/config.yml, .sauce/config.yml, examples/allure-plugin/.sauce/config.yml, examples/cucumber/.sauce/config.yml, examples/typescript/.sauce/config.yml
Direct users to the appropriate repo when filing reports.
=> Add Issue Template

.github/workflows/test.yml, .sauce/config.yml, examples/allure-plugin/.sauce/config.yml, examples/allure-plugin/.sauceignore, examples/allure-plugin/README.md, examples/allure-plugin/package-lock.json, examples/allure-plugin/package.json, examples/cucumber/.sauce/config.yml, examples/cucumber/.sauceignore, examples/cucumber/README.md, examples/cucumber/package-lock.json, examples/typescript/.sauce/config.yml, examples/typescript/.sauceignore, examples/typescript/README.md, examples/typescript/package-lock.json, examples/typescript/package.json
Update examples to showcase the new npm dependency management feature.
=> Utilize New NPM Dependency Management

.gitpod.yml
Pass the build name into the .gitpod.io file and use it in the saucectl run command
=> Pass build and region into gitpod.yml

v1/examples/cypress-grep/.sauce/config.yml, v1/examples/cypress-grep/.sauceignore, v1/examples/cypress-grep/README.md, v1/examples/cypress-grep/cypress.config.js, v1/examples/cypress-grep/cypress/e2e/examples/actions.cy.js, v1/examples/cypress-grep/cypress/support/e2e.js, v1/examples/cypress-grep/package-lock.json, v1/examples/cypress-grep/package.json
* cypress-grep package moved to @cypress/grep, update example accordingly
* Clean up config.yml to more easily highlight the relevant configuration
* Update README to include clear explanations of the relevant configuration.
=> Update grep example

.github/workflows/test-v1.yml, .github/workflows/test-v1alpha.yml
- Rely on `saucectl-run-action@v3`
- Remove unnecessary steps
=> Simplify pipelines

v1/examples/cucumber/.cypress-cucumber-preprocessorrc.json, v1/examples/cucumber/.sauce/config.yml, v1/examples/cucumber/.sauceignore, v1/examples/cucumber/README.md, v1/examples/cucumber/cypress.config.js, v1/examples/cucumber/package-lock.json, v1/examples/cucumber/package.json
Job example: https://app.saucelabs.com/tests/a3d9104b20f64d798f69927e4587902c
BTW, I found the uploaded `esbuild` is OS sensitive. So it'd throw error when I installed and uploaded `esbuild` on mac machine but executed it on Sauce Windows platform.
```
npm ERR! Error: Command failed: node D:\sauce-cypress-runner\10.2.0\bundle\__project__\node_modules\@badeball\cypress-configuration\node_modules\esbuild\bin\esbuild --version
npm ERR! D:\sauce-cypress-runner\10.2.0\bundle\__project__\node_modules\@badeball\cypress-configuration\node_modules\esbuild\bin\esbuild:1
npm ERR! ELF
npm ERR! ^
npm ERR! 
npm ERR! SyntaxError: Invalid or unexpected token
```
`esbuild@0.17.18` is required by `@badeball/cypress-cucumber-preprocessor`.
=> feat: Add cucumber json report example

.circleci/config.yml, v1/.sauce/config.yml, v1/examples/allure-plugin/.sauce/config.yml, v1/examples/cucumber/.sauce/config.yml, v1/examples/cypress-grep/.sauce/config.yml, v1/examples/typescript/.sauce/config.yml, v1/examples/webkit/.sauce/config.yml
[DEVX-2541]
[DEVX-2541]: https://saucedev.atlassian.net/browse/DEVX-2541?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: bump to latest cypress

v1/.sauce/config.yml, v1/examples/allure-plugin/.sauce/config.yml, v1/examples/cucumber/.sauce/config.yml, v1/examples/cypress-grep/.sauce/config.yml, v1/examples/typescript/.sauce/config.yml, v1/examples/webkit/.sauce/config.yml
[DEVX-2615]
[DEVX-2615]: https://saucedev.atlassian.net/browse/DEVX-2615?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: Bump examples to latest

.github/workflows/test-v1.yml, v1/.sauce/config.yml
Update to the latest and greatest.
=> ci: bump framework version

v1/.sauce/config.yml, v1/examples/allure-plugin/.sauce/config.yml, v1/examples/cucumber/.sauce/config.yml, v1/examples/cypress-grep/.sauce/config.yml, v1/examples/typescript/.sauce/config.yml, v1/examples/webkit/.sauce/config.yml
[DEVX-2729]
[DEVX-2729]: https://saucedev.atlassian.net/browse/DEVX-2729?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: Bump examples to latest framework version

v1/.sauce/config.yml
[DEVX-2899]
[DEVX-2899]: https://saucedev.atlassian.net/browse/DEVX-2899?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: bump to latest

.github/PULL_REQUEST_TEMPLATE.md, v1/.sauce/config.yml, v1/examples/allure-plugin/.sauce/config.yml, v1/examples/cucumber/.sauce/config.yml, v1/examples/cypress-grep/.sauce/config.yml, v1/examples/multi-reporter/.sauce/config.yml, v1/examples/typescript/.sauce/config.yml, v1/examples/webkit/.sauce/config.yml
=> chore: showcase spotlight reporter

v1/.sauce/config.yml, v1/examples/allure-plugin/.sauce/config.yml, v1/examples/cucumber/.sauce/config.yml, v1/examples/cypress-grep/.sauce/config.yml, v1/examples/multi-reporter/.sauce/config.yml, v1/examples/multi-reporter/package-lock.json, v1/examples/multi-reporter/package.json, v1/examples/typescript/.sauce/config.yml, v1/examples/webkit/.sauce/config.yml
=> chore: Bump Cypress version

v1/.sauce/config.yml, v1/examples/allure-plugin/.sauce/config.yml, v1/examples/cucumber/.sauce/config.yml, v1/examples/cypress-grep/.sauce/config.yml, v1/examples/multi-reporter/.sauce/config.yml, v1/examples/typescript/.sauce/config.yml
=> chore: Bump cypress 13.13.1

v1/.sauce/config.yml, v1/examples/allure-plugin/.sauce/config.yml, v1/examples/cucumber/.sauce/config.yml, v1/examples/cypress-grep/.sauce/config.yml, v1/examples/multi-reporter/.sauce/config.yml, v1/examples/typescript/.sauce/config.yml, v1/examples/webkit/.sauce/config.yml
[DEVX-3044]
[DEVX-3044]: https://saucedev.atlassian.net/browse/DEVX-3044?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: Bump examples to latest supported framework

v1/examples/cucumber/.sauce/config.yml, v1/examples/cucumber/.sauceignore, v1/examples/cucumber/README.md, v1/examples/cucumber/package-lock.json, v1/examples/cucumber/package.json
[DEVX-3077]
[DEVX-3077]: https://saucedev.atlassian.net/browse/DEVX-3077?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: Update example to use usePackageLock

v1/.sauce/config.yml, v1/examples/allure-plugin/.sauce/config.yml, v1/examples/component-testing-react-cra5/.sauce/config.yml, v1/examples/cucumber/.sauce/config.yml, v1/examples/cucumber/package-lock.json, v1/examples/cucumber/package.json, v1/examples/cypress-grep/.sauce/config.yml, v1/examples/multi-reporter/.sauce/config.yml, v1/examples/typescript/.sauce/config.yml, v1/examples/webkit/.sauce/config.yml
[DEVX-3114]
[DEVX-3114]: https://saucedev.atlassian.net/browse/DEVX-3114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: bump examples to latest cypress version

.github/workflows/test-v1.yml, v1/examples/multi-reporter/.sauce/config.yml, v1/examples/multi-reporter/.sauceignore, v1/examples/multi-reporter/README.md, v1/examples/multi-reporter/cypress.config.js, v1/examples/multi-reporter/cypress/support/e2e.js, v1/examples/multi-reporter/package-lock.json, v1/examples/multi-reporter/package.json, v1/examples/multi-reporter/reporter-config.json
[INT-171]
[INT-171]: https://saucedev.atlassian.net/browse/INT-171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: Update cypress multi reporter example

v1/.sauce/config.yml, v1/examples/allure-plugin/.sauce/config.yml, v1/examples/component-testing-react-vite-ts/.sauce/config.yml, v1/examples/component-testing-react-vite-ts/package-lock.json, v1/examples/component-testing-react-vite-ts/package.json, v1/examples/cucumber/.sauce/config.yml, v1/examples/cucumber/package-lock.json, v1/examples/cucumber/package.json, v1/examples/cypress-grep/.sauce/config.yml, v1/examples/multi-reporter/.sauce/config.yml, v1/examples/multi-reporter/package-lock.json, v1/examples/multi-reporter/package.json, v1/examples/typescript/.sauce/config.yml, v1/examples/webkit/.sauce/config.yml
Update Cypress framework to the latest version.
=> [INT-186] update Cypress to 14.3.2
